In [ ]:
%%capture
!wget https://corgis-edu.github.io/corgis/datasets/csv/broadway/broadway.csv

# Broadway
- Imprimir: ¿Qué columnas tiene?
- ¿Qué significa cada columna?
- ¿Qué obras diferentes se presentaron?
¿Cuántas obras diferentes se presentaron?
- Genera un DataFrame sólo con una las columnas de las obras, los teatros, los asistentes y el ingreso neto.
- ¿En cuántos teatros se ha presentado Mamma Mia! en Broadway?
- ¿Qué obras se han presentado en más de un teatro?
- ¿Qué otras obras se han presentado en los mismos teatros que Mamma Mia! ?

Para la obra de Mamma Mia!:
- Para cada semana, calcular el valor promedio por boleto

Para todos los teatros:
- Calcular la asistencia promedio del teatro
- ¿Cuál es el teatro con el nombre más largo?
- ¿Cuál es la obra con más palabras en su título?

In [ ]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [ ]:
df1 = pd.read_csv("broadway.csv")
df1

,Date.Day,Date.Full,Date.Month,Date.Year,Show.Name,Show.Theatre,Show.Type,Statistics.Attendance,Statistics.Capacity,Statistics.Gross,Statistics.Gross Potential,Statistics.Performances
0,26,8/26/1990,8,1990,Tru,Booth,Play,5500,88,134456,0,8
1,24,3/24/1991,3,1991,Miss Saigon,Broadway,Musical,1737,100,100647,0,0
2,31,3/31/1991,3,1991,Miss Saigon,Broadway,Musical,12160,100,634424,0,0
3,7,4/7/1991,4,1991,Miss Saigon,Broadway,Musical,13921,100,713353,0,0
4,14,4/14/1991,4,1991,Miss Saigon,Broadway,Musical,10973,90,573981,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...
31291,14,8/14/2016,8,2016,The Humans,Schoenfeld,Play,7234,87,603770,62,8
31292,14,8/14/2016,8,2016,The Lion King,Minskoff,Musical,13485,99,2233894,97,8
31293,14,8/14/2016,8,2016,The Phantom Of The Opera,Majestic,Musical,10966,85,999632,66,8
31294,14,8/14/2016,8,2016,Waitress,Brooks Atkinson,Musical,8058,96,990128,97,8
31295,14,8/14/2016,8,2016,Wicked,Gershwin,Musical,13804,95,1779664,100,8

In [ ]:
df1["Show.Name"]

Shows = df1["Show.Name"].unique()
Shows

In [ ]:
print (len(Shows))

820

In [ ]:
# Genera un DataFrame sólo con una las columnas de las obras, los teatros, los asistentes y el ingreso neto.
#short_df = DataFrame (df1, columns=["Show.Name", "Show.Theatre", "Statistics.Attendance", "Statistics.Gross"], index=df1["Show.Name"])
short_df = DataFrame (df1, columns=["Show.Name", "Show.Theatre", "Statistics.Attendance", "Statistics.Gross"])

short_df.head(5)

     Show.Name Show.Theatre  Statistics.Attendance  Statistics.Gross
0          Tru        Booth                   5500            134456
1  Miss Saigon     Broadway                   1737            100647
2  Miss Saigon     Broadway                  12160            634424
3  Miss Saigon     Broadway                  13921            713353
4  Miss Saigon     Broadway                  10973            573981

In [ ]:

#¿Qué obras se han presentado en más de un teatro?

In [ ]:

short_df.index = df1["Show.Name"]
for each_show in Shows:
  filtered_df = short_df.loc[each_show, ["Show.Theatre"]]
  print (type (filtered_df["Show.Theatre"]))
  #print (filtered_df["Show.Theatre"].unique())